version: "3"
services:
  web:
    restart: always
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_app
